### ISSUE TITLE
delta service fails to sent delta's to stats service

### ISSUE THREAD

**Issue by nvdk** [redpencilio/app-http-logger#7]
I'm getting a lot of errors like these:
```
delta_1_e07bc27f2050 | Could not send request POST http://stats/.mu/delta
delta_1_e07bc27f2050 | { Error: socket hang up
delta_1_e07bc27f2050 |     at createHangUpError (_http_client.js:323:15)
delta_1_e07bc27f2050 |     at Socket.socketOnEnd (_http_client.js:426:23)
delta_1_e07bc27f2050 |     at Socket.emit (events.js:187:15)
delta_1_e07bc27f2050 |     at Socket.EventEmitter.emit (domain.js:441:20)
delta_1_e07bc27f2050 |     at endReadableNT (_stream_readable.js:1094:12)
delta_1_e07bc27f2050 |     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
delta_1_e07bc27f2050 | NOT RETRYING
```
I've verified `stats` resolves to the correct ip in the delta container. Logging this here so we can investigate once we find some time for it.

**Comment by nvdk** [comment]
FYI fixed in https://github.com/redpencilio/docker-stats-service/commit/7dc729d96995a04c5cbce4a32e235e3d1a6a63de
